<?xml version="1.0" encoding="utf-8"?><Database Name="Sneaker" Class="SneakerManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NhapLaiMatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Loai" Member="Loais">
    <Type Name="Loai">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Loai_SanPham" Member="SanPhams" ThisKey="MaLoai" OtherKey="MaLoai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.PhanHoi" Member="PhanHois">
    <Type Name="PhanHoi">
      <Column Name="Maph" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Noidung" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTaSanPham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDonHang" />
      <Association Name="Loai_SanPham" Member="Loai" ThisKey="MaLoai" OtherKey="MaLoai" Type="Loai" IsForeignKey="true" />
    </Type>
  </Table>
</Database>